### ISSUE TITLE
Running script for Training throws error 

### ISSUE THREAD

**Issue by vaibhav016** [YukunLi99/CoLeCLIP#1]
While running the following script CUDA_VISIBLE_DEVICES=0 python main.py \
    --config-file configs/CoLeCLIP.yaml \
    DATASETS.TRAIN  [\'Aircraft\'] \
    SOLVER.EPOCHS 20 \
    METHOD.NUM_PROMPTS_PER_TASK 1 \
    METHOD.STAGE_STEP 0.5 \
    SAVE ckpt/exp_CoLeCLIP_order1 \
    METHOD.VOCAB_PTH None \
    METHOD.TASK_CLS_DICT None \
    SOLVER.LR 0.001 \
    METHOD.PERCENTAGE 0.7 \
    METHOD.MOM_COEF 0.1 \
    METHOD.MEM True
    
    an error is caught at line 217 in /CoLeCLIP/method/CoLeCLIP.py 
cur_classes = self.task_class_dict[self.num_tasks]

Error : KeyError: 0

It seems that  self.task_class_dict is not found.

**Comment by YukunLi99** [comment]
Based on the error message, it seems likely that` self.task_class_dict` could be an empty dictionary. I recommend verifying the contents of `self.task_class_dict`. If it is indeed empty, please ensure that `cfg.METHOD.USE_VOC` is set to True and verify if [`self.preprocess_vocab()`](https://github.com/YukunLi99/CoLeCLIP/blob/c6f8d34e56ce86ba562693f71c18ccf0df686761/engine/trainer.py#L342) has been executed.

**Comment by vaibhav016** [comment]
Thanks a lot for your prompt reply. it worked. Closing this isse.
